---
# handlers file for ansible-role-haproxy

- name: Restart haproxy
  systemd:
    name: "haproxy"
    state: "restarted"
    enabled: "yes"
  retries: 3
  when: not ansible_check_mode and ansible_facts.services is defined

- name: Restart firewalld
  systemd:
    name: "firewalld"
    state: "restarted"
    enabled: "yes"
  retries: 3
  when: not ansible_check_mode and ansible_facts.services['firewalld.service'].state == 'running'
